/* AstraLearn V2 — contenu scolaire + moteur de quiz */
(function(){
  // Inversement demandé : 3e avant 4e dans le sélecteur.
  const oldData = window.data;
  if (oldData) {
    window.data = {'3ème':oldData['3ème'],'4ème':oldData['4ème'],'2nde':oldData['2nde'],'1ère':oldData['1ère'],'Terminale':oldData['Terminale']};
  }

  // Contenu structuré : chaque chapitre possède 2 fiches et 2 questions de quiz.
  // Pour les chapitres dont le nom varie selon le niveau, le moteur construit un contenu adapté au thème.
  const CONTENT = {
    'Calcul littéral & équations': {
      f:['Le calcul littéral utilise des lettres pour représenter des nombres. Développer consiste à distribuer un facteur : a(b+c)=ab+ac. Factoriser fait l’inverse. Pour résoudre une équation, on transforme progressivement l’égalité en conservant l’équivalence entre les deux membres.','Méthode : 1) réduire les expressions semblables ; 2) regrouper les termes en x d’un côté et les nombres de l’autre ; 3) diviser par le coefficient de x ; 4) vérifier la solution dans l’équation de départ.'],
      q:[['Développer 4(x−3) donne :',['4x−3','4x−12','x−12','4x+12'],'4x−12'],['Quelle est la solution de 3x+2=14 ?',['2','3','4','5'],'4']]},
    'Théorème de Pythagore': {
      f:['Dans un triangle rectangle, le carré de la longueur de l’hypoténuse est égal à la somme des carrés des deux autres côtés : c²=a²+b². L’hypoténuse est le côté opposé à l’angle droit.','Pour calculer une longueur, écris l’égalité de Pythagore, remplace les longueurs connues puis prends la racine carrée si nécessaire. Pour démontrer qu’un triangle est rectangle, utilise la réciproque.'],
      q:[['Un triangle rectangle a pour côtés de l’angle droit 6 cm et 8 cm. Son hypoténuse mesure :',['9 cm','10 cm','12 cm','14 cm'],'10 cm'],['Pour appliquer Pythagore, le triangle doit être :',['équilatéral','rectangle','isocèle uniquement','quelconque'],'rectangle']]},
    'Fonctions & statistiques': {
      f:['Une fonction associe à chaque nombre x une unique image f(x). On note souvent cette image f(x). Pour lire une image ou un antécédent, on utilise une expression, un tableau ou une représentation graphique.','En statistique, la moyenne est la somme des valeurs divisée par l’effectif total. La médiane partage une série ordonnée en deux groupes de même effectif. L’étendue est la différence entre le maximum et le minimum.'],
      q:[['Si f(x)=2x−1, alors f(5)=',['8','9','10','11'],'9'],['L’étendue d’une série allant de 4 à 17 est :',['11','12','13','21'],'13']]},
    'Figures de style': {
      f:['La comparaison rapproche deux éléments avec un outil comparatif (« comme », « tel », « semblable à »). La métaphore crée un rapprochement sans outil comparatif. La personnification attribue des caractéristiques humaines à une chose.','L’hyperbole exagère pour produire un effet. La litote dit moins pour suggérer davantage. L’anaphore répète un mot ou groupe de mots en début de phrases ou de vers.'],
      q:[['« Ses yeux brillent comme des étoiles » est une :',['comparaison','métaphore','litote','anaphore'],'comparaison'],['« Je meurs de faim » est une :',['euphémisme','hyperbole','périphrase','antiphrase'],'hyperbole']]},
    'Grammaire & classes de mots': {
      f:['La nature d’un mot indique sa catégorie grammaticale : nom, déterminant, adjectif, pronom, verbe, adverbe, préposition, conjonction… La fonction indique son rôle dans la phrase : sujet, COD, COI, attribut, complément circonstanciel…','Pour trouver le sujet, on peut demander « qui est-ce qui ? ». Le COD répond souvent à « qui ? » ou « quoi ? » après le verbe. Le COI est introduit par une préposition comme à ou de.'],
      q:[['Dans « Les élèves lisent le texte », le COD est :',['Les élèves','lisent','le texte','aucun'],'le texte'],['« rapidement » est généralement un :',['nom','adjectif','adverbe','déterminant'],'adverbe']]},
    'Première Guerre mondiale': {
      f:['La Première Guerre mondiale se déroule de 1914 à 1918. Elle oppose notamment les puissances de l’Entente aux Empires centraux. Le conflit devient une guerre totale mobilisant soldats, économies et populations.','Sur le front occidental, la guerre de tranchées s’accompagne de combats extrêmement meurtriers. En 1917, les États-Unis entrent en guerre et la Russie se retire progressivement du conflit après la révolution.'],
      q:[['La Première Guerre mondiale se termine en :',['1914','1916','1918','1923'],'1918'],['Le front occidental est notamment marqué par :',['les tranchées','la guerre froide','l’absence de combats','une guerre uniquement navale'],'les tranchées']]},
    'Seconde Guerre mondiale': {
      f:['La Seconde Guerre mondiale se déroule de 1939 à 1945. Elle oppose principalement les puissances de l’Axe aux Alliés. Le conflit est mondial et implique fortement les civils.','Le génocide des Juifs et des Tsiganes est organisé par l’Allemagne nazie et ses collaborateurs. Les débarquements alliés de 1944 accélèrent la libération de l’Europe occidentale.'],
      q:[['La Seconde Guerre mondiale se termine en :',['1939','1942','1945','1950'],'1945'],['Le génocide des Juifs et des Tsiganes est aussi appelé :',['Shoah','Renaissance','Guerre froide','Décolonisation'],'Shoah']]},
    'Démocratie & citoyenneté': {
      f:['Une démocratie repose notamment sur la souveraineté des citoyens, des élections, des libertés publiques et l’existence de règles permettant l’alternance du pouvoir.','La citoyenneté donne des droits mais aussi des responsabilités. En France, le vote, le respect de la loi et la participation à la vie collective sont des éléments importants de la citoyenneté.'],
      q:[['Dans une démocratie, les citoyens peuvent notamment :',['participer aux élections','supprimer les lois seuls','choisir toujours les juges','ne jamais respecter les règles'],'participer aux élections'],['La Constitution sert notamment à :',['organiser les pouvoirs','fixer les notes scolaires','remplacer toutes les lois','interdire les élections'],'organiser les pouvoirs']]},
    'Mouvement & vitesse': {
      f:['La vitesse moyenne se calcule par v=d/t, avec une distance d et une durée t. Il faut conserver des unités cohérentes avant de calculer.','Un mouvement peut être décrit par rapport à un référentiel. La trajectoire est l’ensemble des positions successives d’un objet. Elle peut être rectiligne, circulaire ou curviligne.'],
      q:[['Une voiture parcourt 120 km en 2 h. Sa vitesse moyenne est :',['40 km/h','60 km/h','80 km/h','120 km/h'],'60 km/h'],['La trajectoire est :',['la masse de l’objet','l’ensemble de ses positions successives','sa température','sa durée'],'l’ensemble de ses positions successives']]},
    'Électricité': {
      f:['Dans un circuit en série, l’intensité est la même en tout point. Dans un circuit avec des branches en dérivation, la tension est la même aux bornes des dipôles placés en parallèle.','La loi d’Ohm s’écrit U=R×I pour un conducteur ohmique. U se mesure en volts, R en ohms et I en ampères.'],
      q:[['La loi d’Ohm est :',['U=RI','U=R/I','I=UR','R=UI'],'U=RI'],['L’unité de la résistance électrique est :',['volt','ampère','ohm','watt'],'ohm']]},
    'Transformations chimiques': {
      f:['Lors d’une transformation chimique, des réactifs sont consommés et de nouveaux produits apparaissent. Les atomes sont conservés : ils se réarrangent pour former de nouvelles molécules.','Une équation chimique doit respecter la conservation des éléments. Les coefficients placés devant les formules permettent d’équilibrer le nombre d’atomes de chaque élément.'],
      q:[['Lors d’une réaction chimique, les atomes :',['disparaissent','sont créés','se réarrangent','deviennent toujours de l’énergie'],'se réarrangent'],['Les substances présentes au début d’une réaction sont les :',['produits','réactifs','solvants uniquement','ions uniquement'],'réactifs']]},
    'Génétique': {
      f:['L’ADN porte une information génétique organisée en gènes. Un gène peut exister sous différentes versions appelées allèles. Les chromosomes sont constitués notamment d’ADN.','La reproduction sexuée mélange les patrimoines génétiques des parents. Des mutations peuvent modifier la séquence d’ADN et contribuer à la diversité génétique.'],
      q:[['Un gène est :',['une cellule','une portion d’ADN portant une information','un organe','une espèce'],'une portion d’ADN portant une information'],['Les différentes versions d’un même gène sont des :',['allèles','organes','enzymes','chromatides uniquement'],'allèles']]},
    'Évolution': {
      f:['Les populations évoluent au fil des générations lorsque la fréquence de certains caractères génétiques change. Les mutations et la sélection naturelle participent à la diversité du vivant.','La sélection naturelle favorise, dans un environnement donné, les caractères qui augmentent les chances de survie ou de reproduction. L’évolution concerne les populations, pas les individus isolés.'],
      q:[['L’évolution concerne principalement :',['les individus pendant leur vie','les populations au fil des générations','uniquement les fossiles','uniquement les bactéries'],'les populations au fil des générations'],['La sélection naturelle dépend notamment :',['de l’environnement','de la couleur du cahier','de la météo d’un seul jour','des notes scolaires'],'de l’environnement']]},
    'Risques et environnement': {
      f:['Un risque résulte de la rencontre entre un aléa et des enjeux exposés. Les sociétés peuvent réduire certains risques grâce à la prévention, aux aménagements et à l’information.','Les activités humaines modifient les écosystèmes et peuvent augmenter certaines pressions : pollution, artificialisation, surexploitation ou changement climatique. La prévention cherche à limiter les dommages.'],
      q:[['Un risque associe notamment :',['un aléa et des enjeux','deux températures','une note et un coefficient','deux espèces seulement'],'un aléa et des enjeux'],['La prévention sert à :',['augmenter l’exposition','réduire les conséquences possibles','supprimer tous les phénomènes naturels','ignorer le danger'],'réduire les conséquences possibles']]},
    'Present perfect': {
      f:['Le present perfect se forme avec have/has + participe passé. Il relie une action passée à une situation présente ou parle d’une expérience sans préciser un moment passé terminé.','Attention à ne pas le confondre avec le past simple : le past simple situe une action terminée dans le passé, souvent avec un repère temporel précis.'],
      q:[['She ___ visited London.',['has','have','did','was'],'has'],['« I went there yesterday » utilise :',['present perfect','past simple','present continuous','future'],'past simple']]},
    'Past simple & past continuous': {
      f:['Le past simple sert à raconter une action terminée dans le passé. Le past continuous (was/were + -ing) décrit une action en cours à un moment donné du passé.','On peut combiner les deux : « I was studying when he called. » L’action longue en cours est au past continuous ; l’événement qui l’interrompt est au past simple.'],
      q:[['« They were playing » est au :',['past simple','past continuous','present perfect','future'],'past continuous'],['Dans « I was sleeping when she called », « called » est au :',['past simple','past continuous','present perfect','present simple'],'past simple']]},
    'La poésie': {
      f:['La poésie joue sur les sons, le rythme, les images et la disposition des mots. Un poème peut être en vers réguliers ou libres et utiliser des rimes, des répétitions et des figures de style.','Pour analyser un poème, observe d’abord la situation d’énonciation, puis le rythme, les sonorités, les images et les thèmes. Cite précisément le texte pour justifier chaque interprétation.'],
      q:[['Une strophe est :',['un groupe de vers','un seul mot','un chapitre','une figure de style'],'un groupe de vers'],['Une comparaison utilise généralement :',['un outil comparatif','uniquement une rime','une équation','une date'],'un outil comparatif']]},
    'Le roman': {
      f:['Le roman est un récit long qui met en scène des personnages dans une histoire. Le narrateur peut être personnage ou extérieur à l’histoire. Le point de vue peut être interne, externe ou omniscient.','Pour analyser un extrait, distingue auteur, narrateur et personnage. Étudie la construction du récit, les descriptions, les paroles rapportées et le point de vue pour comprendre les effets produits.'],
      q:[['Le point de vue omniscient signifie que le narrateur :',['sait tout des personnages','ne décrit rien','est forcément un personnage','raconte uniquement au présent'],'sait tout des personnages'],['Le narrateur est :',['toujours l’auteur','la voix qui raconte l’histoire','toujours le héros','le lecteur'],'la voix qui raconte l’histoire']]},
    'La littérature d’idées': {
      f:['La littérature d’idées cherche à défendre, discuter ou interroger une idée. Elle peut prendre la forme d’un essai, d’un discours, d’une lettre ou d’un texte argumentatif.','Un argument soutient une thèse ; un exemple rend l’idée concrète. Pour analyser un texte argumentatif, repère la thèse, les arguments, les exemples, les connecteurs logiques et les procédés destinés à convaincre ou persuader.'],
      q:[['La thèse est :',['l’idée défendue','un exemple uniquement','la conclusion d’un calcul','le titre'],'l’idée défendue'],['Un exemple sert notamment à :',['illustrer un argument','supprimer la thèse','changer de sujet','compter les mots'],'illustrer un argument']]},
    'Fonctions': {
      f:['Une fonction associe à chaque nombre x une unique image. Une fonction affine s’écrit f(x)=ax+b et sa représentation graphique est une droite. Le coefficient a indique le taux de variation.','Pour étudier une fonction, on peut calculer des images, chercher des antécédents, dresser un tableau de valeurs et interpréter graphiquement les variations.'],
      q:[['Si f(x)=3x+2, f(4)=',['10','12','14','16'],'14'],['La représentation graphique d’une fonction affine est :',['une droite','un cercle','une parabole uniquement','un point'],'une droite']]},
    'Statistiques & probabilités': {
      f:['Une probabilité mesure la chance qu’un événement se produise et est comprise entre 0 et 1. Dans une situation équiprobable, P(A)=nombre de cas favorables/nombre de cas possibles.','En statistique, moyenne, médiane et écart-type décrivent une série. La médiane sépare la série ordonnée en deux groupes contenant chacun environ la moitié des données.'],
      q:[['Une probabilité vaut toujours :',['entre 0 et 1','entre −1 et 1','plus de 1','exactement 1'],'entre 0 et 1'],['Avec 3 issues favorables sur 10 équiprobables, la probabilité est :',['0,03','0,3','3','10/3'],'0,3']]},
    'Géométrie': {
      f:['En géométrie, les propriétés doivent être choisies en fonction des informations données : parallélisme, perpendicularité, longueurs, angles ou cercles. Une démonstration doit relier clairement hypothèses, propriété et conclusion.','Pour résoudre un problème, réalise une figure propre, note les données, identifie la configuration puis choisis le théorème adapté. N’utilise jamais une propriété sans vérifier ses conditions.'],
      q:[['Une démonstration géométrique doit :',['justifier les étapes','donner seulement le résultat','éviter les propriétés','utiliser toutes les formules possibles'],'justifier les étapes'],['Avant un théorème, il faut vérifier :',['ses conditions d’application','la couleur de la figure','le nombre de pages','la date'],'ses conditions d’application']]},
    'Dérivation': {
      f:['La dérivée mesure localement le taux de variation d’une fonction. Si f est dérivable, f’(a) est le coefficient directeur de la tangente à la courbe au point d’abscisse a.','Pour étudier les variations, on détermine le signe de f’. Si f’ est positive sur un intervalle, f y est croissante ; si elle est négative, f y est décroissante.'],
      q:[['La dérivée donne notamment :',['un taux de variation local','une aire uniquement','une moyenne','une probabilité'],'un taux de variation local'],['Si f’(x)>0 sur un intervalle, f est :',['décroissante','constante','croissante','impossible à étudier'],'croissante']]},
    'Suites': {
      f:['Une suite associe un entier n à un nombre u_n. Une suite peut être définie explicitement par une formule en n ou par récurrence à partir d’un premier terme et d’une relation.','Une suite arithmétique a un écart constant entre deux termes consécutifs. Une suite géométrique a un quotient constant entre deux termes consécutifs.'],
      q:[['Dans une suite arithmétique, la différence u(n+1)−u(n) est :',['constante','toujours nulle','toujours négative','variable obligatoirement'],'constante'],['Dans une suite géométrique, le quotient u(n+1)/u(n) est :',['constant','toujours 0','toujours 1','égal à n'],'constant']]},
    'Probabilités': {
      f:['Une variable aléatoire associe un nombre à chaque issue d’une expérience aléatoire. Sa loi donne les probabilités de ses différentes valeurs.','L’espérance représente une moyenne théorique des valeurs d’une variable aléatoire. Pour une loi discrète, on calcule E(X)=Σx_iP(X=x_i).'],
      q:[['La somme des probabilités d’une loi est :',['0','0,5','1','2'],'1'],['L’espérance est une :',['moyenne théorique','probabilité toujours entière','variance','fréquence observée uniquement'],'moyenne théorique']]},
    'La conscience': {
      f:['La conscience désigne notamment la capacité à avoir des représentations de soi, du monde et de ses propres pensées. En philosophie, il faut distinguer conscience de soi, conscience morale et perception.','Pour construire une réflexion, définis les termes du sujet, formule une problématique et confronte plusieurs thèses. Un exemple ne remplace pas un raisonnement : il sert à l’éclairer ou à le mettre à l’épreuve.'],
      q:[['Une dissertation philosophique doit d’abord :',['analyser les termes du sujet','réciter une conclusion','donner une opinion sans argument','faire uniquement des exemples'],'analyser les termes du sujet'],['Une problématique sert à :',['faire apparaître une difficulté à penser','répéter le sujet','donner directement la réponse','résumer le cours'],'faire apparaître une difficulté à penser']]},
    'La liberté': {
      f:['La liberté peut être comprise comme absence de contrainte, autonomie ou capacité de choisir. Une réflexion philosophique distingue les obstacles extérieurs, les déterminismes et la responsabilité.','Pour traiter « sommes-nous libres ? », confronte par exemple la liberté comme choix à l’idée que nos actions peuvent être influencées par des causes que nous ne maîtrisons pas.'],
      q:[['L’autonomie signifie notamment :',['se donner à soi-même des règles','faire absolument tout ce que l’on veut','ne jamais respecter autrui','être sans aucune cause'],'se donner à soi-même des règles'],['Une contrainte est :',['ce qui limite une possibilité d’action','une liberté parfaite','une preuve mathématique','une émotion uniquement'],'ce qui limite une possibilité d’action']]},
    'La vérité': {
      f:['La vérité concerne l’accord entre ce que l’on affirme et ce qui est. En philosophie, on distingue notamment vérité, opinion, croyance et connaissance justifiée.','Une démarche rationnelle cherche des raisons, confronte les arguments aux faits et accepte la possibilité de corriger une affirmation. La preuve dépend du domaine : mathématique, scientifique, historique ou logique.'],
      q:[['Une opinion est généralement :',['une affirmation qui n’est pas nécessairement démontrée','toujours fausse','toujours scientifique','une preuve'],'une affirmation qui n’est pas nécessairement démontrée'],['Une démonstration mathématique vise à :',['établir rigoureusement une conclusion','exprimer une préférence','raconter une histoire','mesurer une température'],'établir rigoureusement une conclusion']]}
  };

  function generic(subject,chapter){
    const s=subject.toLowerCase();
    if(s.includes('math')) return {f:['Ce chapitre de mathématiques travaille des notions, définitions et propriétés qu’il faut savoir reconnaître et appliquer. Commence par identifier les données et la question posée.','Méthode : écrire la propriété utilisée, remplacer par les données, effectuer les calculs proprement puis vérifier l’ordre de grandeur et l’unité du résultat.'],q:[['Quel réflexe est le plus important en mathématiques ?',['Choisir une formule au hasard','Identifier les données et la propriété adaptée','Ignorer les unités','Donner seulement un nombre'],'Identifier les données et la propriété adaptée'],['Après un calcul, il faut :',['ne jamais vérifier','vérifier le résultat','effacer les étapes','changer de chapitre'],'vérifier le résultat']]};
    if(s.includes('physique')) return {f:['En physique-chimie, on part d’une situation réelle pour construire un modèle. Les grandeurs, unités et lois permettent de relier les données à la question.','Méthode : relever les grandeurs connues, convertir les unités, choisir la relation adaptée, calculer puis donner une réponse avec unité et phrase de conclusion.'],q:[['Avant une application numérique, il faut :',['convertir si nécessaire les unités','ignorer les unités','arrondir toutes les données','inventer une valeur'],'convertir si nécessaire les unités'],['Une réponse scientifique doit idéalement comporter :',['un résultat et son unité','un nombre seul','un titre seulement','aucun calcul'],'un résultat et son unité']]};
    if(s.includes('svt')) return {f:['En SVT, les phénomènes biologiques et géologiques sont expliqués à partir d’observations, de données et de modèles. Les schémas doivent être légendés et reliés à une idée scientifique.','Méthode : décrire les résultats sans les interpréter trop vite, puis expliquer ce qu’ils montrent en mobilisant les connaissances du chapitre.'],q:[['Une observation sert notamment à :',['appuyer une explication','remplacer toutes les connaissances','inventer une conclusion','éviter les données'],'appuyer une explication'],['Dans un schéma scientifique, les légendes doivent être :',['précises et lisibles','absentes','décoratives uniquement','au hasard'],'précises et lisibles']]};
    if(s.includes('français')) return {f:['Pour analyser un texte, distingue les procédés utilisés et l’effet qu’ils produisent. Une citation courte et précise doit être reliée à ton interprétation.','Méthode : présenter l’idée, citer le texte, nommer le procédé ou la notion puis expliquer son effet. En rédaction, organise les paragraphes et relis les accords.'],q:[['Une citation doit être :',['précise et expliquée','isolée sans commentaire','inventée','très longue obligatoirement'],'précise et expliquée'],['Une argumentation efficace utilise :',['des idées justifiées','uniquement des opinions','aucun exemple','des phrases sans lien'],'des idées justifiées']]};
    if(s.includes('histoire')||s.includes('géographie')||s.includes('hggsp')) return {f:['En histoire-géographie, les dates, lieux, acteurs et notions doivent être replacés dans leur contexte. Une chronologie ou une carte permet de structurer les informations.','Méthode : identifier le sujet, délimiter l’espace ou la période, sélectionner les informations pertinentes puis les organiser en réponse construite.'],q:[['Pour analyser un événement historique, il faut notamment :',['le contextualiser','le sortir de son époque','inventer les acteurs','ignorer les dates'],'le contextualiser'],['Une carte sert notamment à :',['représenter spatialement des phénomènes','donner uniquement des dates','remplacer une dissertation','calculer une moyenne'],'représenter spatialement des phénomènes']]};
    if(s.includes('ses')) return {f:['En SES, on distingue les faits, les mécanismes économiques et sociaux et les interprétations. Les notions doivent être définies avant d’être utilisées.','Méthode : définir la notion, présenter le mécanisme, mobiliser un exemple ou une donnée puis expliquer précisément le lien avec la question.'],q:[['Une notion de SES doit être :',['définie précisément','utilisée sans définition','remplacée par un exemple','apprise sans contexte'],'définie précisément'],['Un exemple sert notamment à :',['illustrer un mécanisme','remplacer toute explication','éviter les définitions','changer de sujet'],'illustrer un mécanisme']]};
    if(s.includes('nsi')||s.includes('snt')) return {f:['En numérique, un algorithme décrit une suite d’étapes permettant de résoudre un problème. Les données doivent être représentées dans une structure adaptée aux opérations attendues.','Méthode : préciser les entrées, les traitements et les sorties. Tester sur plusieurs cas permet de repérer les erreurs et les cas particuliers.'],q:[['Un algorithme est :',['une suite d’instructions','une image','un mot de passe','un câble'],'une suite d’instructions'],['Tester un programme sert à :',['détecter des erreurs','supprimer le code','éviter les cas particuliers','changer le langage automatiquement'],'détecter des erreurs']]};
    if(s.includes('anglais')||s.includes('lv2')) return {f:['Pour progresser en langue, apprends les structures dans des phrases complètes et réutilise régulièrement le vocabulaire. Les temps verbaux se choisissent selon la situation et le repère temporel.','Méthode : repérer le temps demandé, identifier le sujet, conjuguer l’auxiliaire si nécessaire puis vérifier l’ordre des mots et les accords.'],q:[['Pour apprendre du vocabulaire, il vaut mieux :',['le réutiliser en contexte','le lire une seule fois','apprendre uniquement des listes isolées','éviter les phrases'],'le réutiliser en contexte'],['En expression, il faut :',['construire des phrases claires','traduire mot à mot systématiquement','éviter les connecteurs','ignorer la grammaire'],'construire des phrases claires']]};
    if(s.includes('philosophie')) return {f:['Une notion philosophique doit être définie avec précision puis discutée. Il faut distinguer les différents sens d’un terme avant de répondre à la question.','Méthode : analyser le sujet, faire émerger une tension, formuler une problématique, construire des parties argumentées et utiliser des exemples ou références pour tester les idées.'],q:[['Une problématique philosophique doit :',['faire apparaître une difficulté réelle','répéter le sujet','donner directement la conclusion','éviter les distinctions'],'faire apparaître une difficulté réelle'],['Une thèse est :',['une position défendue par un raisonnement','un exemple isolé','un titre','une question sans réponse'],'une position défendue par un raisonnement']]};
    return {f:['Cette fiche présente les notions essentielles du chapitre « '+chapter+' ». Commence par apprendre les définitions, les mots-clés et les exemples du cours.','Méthode : transforme ensuite les notions en questions, entraîne-toi à répondre sans regarder le cours et reviens sur chaque erreur.'],q:[['Pour bien réviser ce chapitre, il faut surtout :',['se tester activement','relire sans réfléchir','apprendre uniquement les titres','éviter les exercices'],'se tester activement'],['Après une erreur, le bon réflexe est de :',['comprendre pourquoi elle est arrivée','passer immédiatement à autre chose','effacer la question','mémoriser uniquement la réponse'],'comprendre pourquoi elle est arrivée']]};
  }

  function chapterContent(subject,chapter){ return CONTENT[chapter] || generic(subject,chapter); }

  // Correction détaillée sous chaque réponse, bonne ou mauvaise.
  window.openChapter = function(subject,chapter){
    const d=chapterContent(subject,chapter); const box=document.getElementById('learn-box');
    box.innerHTML='<div class="learn-head"><div><span class="tag">'+level+' · '+subject+'</span><h2>'+chapter+'</h2><p class="small">2 fiches détaillées · 2 quiz · correction immédiate</p></div><button class="btn btn-ghost" onclick="openSubject(\''+subject.replace(/'/g,"\\'")+'\')">← Chapitres</button></div><div class="tabs"><button class="tab active" onclick="showLesson(0)">Fiche 1 — Essentiel</button><button class="tab" onclick="showLesson(1)">Fiche 2 — Méthode</button><button class="tab" onclick="showQuiz(0)">Quiz 1</button><button class="tab" onclick="showQuiz(1)">Quiz 2</button></div><div id="lesson-area" class="glass lesson"></div><div id="quiz-area"></div>';
    window.currentChapter=d; showLesson(0);
  };
  window.showQuiz = function(n){
    const d=window.currentChapter,q=d.q[n]; document.getElementById('lesson-area').innerHTML='';
    const explanation = 'La réponse « '+q[2]+' » est correcte car elle correspond directement à la règle, à la définition ou au calcul présenté dans la fiche. Pour progresser, retiens la notion puis refais la question sans regarder la correction.';
    document.getElementById('quiz-area').innerHTML='<div class="glass quiz-card"><span class="tag">Quiz '+(n+1)+'</span><h3>'+q[0]+'</h3>'+q[1].map(o=>'<button class="quiz-option" onclick="answerQuiz(this,\''+o.replace(/'/g,"\\'")+'\',\''+q[2].replace(/'/g,"\\'")+'\',\''+explanation.replace(/'/g,"\\'")+'\')">'+o+'</button>').join('')+'<div class="quiz-result" id="qr"></div></div>';
  };
  window.answerQuiz = function(btn,given,correct,explanation){
    document.querySelectorAll('.quiz-option').forEach(x=>x.disabled=true); const ok=given===correct; const r=document.getElementById('qr');
    r.className='quiz-result '+(ok?'good':'bad');
    r.innerHTML=(ok?'✅ <b>Bonne réponse !</b>':'❌ <b>Pas tout à fait.</b>')+'<div class="detailed-correction"><strong>Correction détaillée</strong><p><b>Réponse correcte :</b> '+correct+'.</p><p>'+explanation+'</p>'+(ok?'':'<p><b>À retenir :</b> relis la fiche correspondante puis refais la question pour vérifier que tu sais expliquer la règle, pas seulement reconnaître la réponse.</p>')+'</div>';
    let xp=Number(localStorage.getItem('astralearn_xp')||0)+(ok?25:5);localStorage.setItem('astralearn_xp',xp);showToast((ok?'+25':' +5')+' XP');
  };

  const style=document.createElement('style');style.textContent='.detailed-correction{margin-top:12px;padding:14px;border-radius:14px;background:rgba(103,232,249,.06);border:1px solid var(--line);font-weight:400;line-height:1.6}.detailed-correction strong{color:var(--cyan)}.quiz-result.good{color:var(--ok)}.quiz-result.bad{color:#ff8cbf}.quiz-result p{margin:7px 0;color:var(--text)}';document.head.appendChild(style);
})();
